# Generated by Django 3.1.7 on 2021-06-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210606_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
